[package]
name = "sic_core"
version = "0.17.0"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
description = "Component of the sic cli: re-exports global dependencies to sub-crates."
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/foresterre/sic"

[dependencies]
image = { version = "0.23.14", features = ["avif"] }
thiserror = "1.0.24"
