[package]
name = "sic_parser"
version = "0.11.0"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
description = "Component of the sic cli: parser for the image operation script used by sic."
edition = "2018"
license-file = "../../LICENSE"
repository = "https://github.com/foresterre/sic"

[dependencies]
sic_core = { path = "../sic_core"}
sic_image_engine = { path = "../sic_image_engine" }

pest = "2.1.2"
pest_derive = "2.0.1"
thiserror = "1.0.18"

[dev-dependencies]
sic_testing = { path = "../sic_testing" }
parameterized = "0.1.1"

[features]
imageproc-ops = []