[package]
name = "sic_io"
version = "0.10.0"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
edition = "2018"
license-file = "../LICENSE"

[dependencies]
sic_core = { path = "../sic_core" }

[dev-dependencies]
sic_testing = { path = "../sic_testing" }