[package]
name = "sic_io"
version = "0.11.0"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
description = "Component of the sic cli: provides accessible i/o around image formats."
edition = "2018"
license-file = "../../LICENSE"
repository = "https://github.com/foresterre/sic"

[dependencies]
sic_core = { path = "../sic_core"}

thiserror = "1.0.18"

[dev-dependencies]
sic_testing = { path = "../sic_testing" }